# infra/docker/dockerfile.api

FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY ../../requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app directory
COPY ../../app /app


# Run FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
